# Lesson 6 Numpy

In [24]:
import numpy as np

### Reshape Array

In [25]:
my_1D_array = np.array([1, 2, 3, 4, 5])
print(my_1D_array.shape)     #(5,) -> 5 rows and 0 columns

my_2D_array = np.array([[1, 2],[3, 4],[6,5]])
print(my_2D_array.shape)     #(3, 2) -> 3 rows and 2 columns 

(5,)
(3, 2)


In [26]:
change_array = numpy.array([1,2,3,4,5,6,7])
change_array.shape = (3, 2)
print(change_array)

ValueError: cannot reshape array of size 7 into shape (3,2)

In [27]:
change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print(change_array)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
my_array = numpy.array([1,2,3,4,5,6])
print(np.reshape(my_array,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


### Transpose & Flatten

In [29]:
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(numpy.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


In [30]:
my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print(my_array.flatten())

[1 2 3 4 5 6]


### Concatenate

In [33]:
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])

print(np.concatenate((array_1, array_2), axis = 1))

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]
